/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package tasks_pkg

import "foulefactoryapi_lib/models_pkg"

/*
 * Interface for the TASKS_IMPL
 */
type TASKS interface {
    UpdateTasksValidate (*models_pkg.TaskValidationWriterServiceModel, *string) (interface{}, error)

    GetTasksGetAnswerChoices (int64, *string) (interface{}, error)

    GetTasksGetAnswerTexts (int64, *string) (interface{}, error)

    GetTasksGet (int64, *string) (interface{}, error)
}

/*
 * Factory for the TASKS interaface returning TASKS_IMPL
 */
func NewTASKS() TASKS {
    return &TASKS_IMPL{}
}