/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package account_pkg

import "foulefactoryapi_lib/models_pkg"

/*
 * Interface for the ACCOUNT_IMPL
 */
type ACCOUNT interface {
    GetAccountValidateTransaction (string, *string) (interface{}, error)

    CreateAccountPayIn (*models_pkg.PayinServiceModel, *string) (interface{}, error)

    GetAccountGetWallet () (interface{}, error)

    CreateAccountCreateAccount (*models_pkg.AccountWriterServiceModel, *string) (interface{}, error)

    GetAccountGet () (interface{}, error)
}

/*
 * Factory for the ACCOUNT interaface returning ACCOUNT_IMPL
 */
func NewACCOUNT() ACCOUNT {
    return &ACCOUNT_IMPL{}
}