/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package taskanswertexts_pkg


/*
 * Interface for the TASKANSWERTEXTS_IMPL
 */
type TASKANSWERTEXTS interface {
    GetTaskAnswerTextsGet (int64, *string) (interface{}, error)
}

/*
 * Factory for the TASKANSWERTEXTS interaface returning TASKANSWERTEXTS_IMPL
 */
func NewTASKANSWERTEXTS() TASKANSWERTEXTS {
    return &TASKANSWERTEXTS_IMPL{}
}