/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package templates_pkg

import "foulefactoryapi_lib/models_pkg"

/*
 * Interface for the TEMPLATES_IMPL
 */
type TEMPLATES interface {
    CreateTemplatesCreateTemplate (*models_pkg.TemplateNewWriterServiceModel, *string) (interface{}, error)

    GetTemplatesGetTemplates () (interface{}, error)

    GetTemplatesGetTemplate (int64, *string) (interface{}, error)
}

/*
 * Factory for the TEMPLATES interaface returning TEMPLATES_IMPL
 */
func NewTEMPLATES() TEMPLATES {
    return &TEMPLATES_IMPL{}
}