/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package projects_pkg

import "foulefactoryapi_lib/models_pkg"

/*
 * Interface for the PROJECTS_IMPL
 */
type PROJECTS interface {
    CreateProjectsCreateProject (*models_pkg.ProjectWriterServiceModel, *string) (interface{}, error)

    GetProjectsGetUserProjects () (interface{}, error)

    GetProjectsGetProjectFiles (int64, *string) (interface{}, error)

    GetProjectsGetProjectTaskLines (int64, *string) (interface{}, error)

    GetProjectsGetProjectTasks (int64, *string) (interface{}, error)

    GetProjectsGet (int64, *string) (interface{}, error)
}

/*
 * Factory for the PROJECTS interaface returning PROJECTS_IMPL
 */
func NewPROJECTS() PROJECTS {
    return &PROJECTS_IMPL{}
}