/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package taskanswerchoices_pkg


/*
 * Interface for the TASKANSWERCHOICES_IMPL
 */
type TASKANSWERCHOICES interface {
    GetTaskAnswerChoicesGet (int64, *string) (interface{}, error)
}

/*
 * Factory for the TASKANSWERCHOICES interaface returning TASKANSWERCHOICES_IMPL
 */
func NewTASKANSWERCHOICES() TASKANSWERCHOICES {
    return &TASKANSWERCHOICES_IMPL{}
}