/*
 * foulefactoryapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

package tasklines_pkg

import "foulefactoryapi_lib/models_pkg"

/*
 * Interface for the TASKLINES_IMPL
 */
type TASKLINES interface {
    CreateTaskLinesCreateTaskLine (*models_pkg.TaskLinesWriterServiceModel, *string) (interface{}, error)

    GetTaskLinesGetTasksByLine (int64, *string) (interface{}, error)

    GetTaskLinesGet (int64, *string) (interface{}, error)
}

/*
 * Factory for the TASKLINES interaface returning TASKLINES_IMPL
 */
func NewTASKLINES() TASKLINES {
    return &TASKLINES_IMPL{}
}